<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Kairos_Sync</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="check.png" />
    <None Remove="Erro.png" />
    <None Remove="Spin.gif" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\API\API.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="check.png" />
    <Resource Include="Erro.png" />
    <Resource Include="Spin.gif" />
  </ItemGroup>

</Project>
